### ISSUE TITLE
Logging out then loggs you right in again on refresh

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/las2peer-frontend-statusbar#7]
Using the logout funtionality of the statusbar and then refreshing the page loggs you back in.
This seems to be due to a cookie being set. Wouldn't it be better if when logging out, that cookie would be invalidated?

**Comment by FBasels** [comment]
For a logout we should end the session of the user at Keycloak (https://www.keycloak.org/docs/latest/securing_apps/index.html#logout). This will end the Single-Sign On session and the user is logged out everywhere else too.

**Comment by FBasels** [comment]
Fixed with [0.3.6](https://github.com/rwth-acis/las2peer-frontend-statusbar/releases/tag/0.3.6)
