### ISSUE TITLE
Left slot

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/las2peer-frontend-statusbar#8]
There is a left slot in the frontend statusbar. I could not find any information on why it is used. Furthermore the title is normally what is positioned on the left.
Can the left slot be removed?

**Comment by pdolif** [comment]
The only place I know where it is used is: https://tech4comp.dbis.rwth-aachen.de/

**Comment by lakhoune** [comment]
> The only place I know where it is used is: https://tech4comp.dbis.rwth-aachen.de/

ah thanks yes that makes sense thanks
